stage 'Code Stability'
build 'CodeStability Spring3Hibernate'
stage 'Code Quality'
build 'TestExecutor Spring3Hibernate'
build 'CodeQuality Spring3Hibernate'
build 'CodeCoverage Spring3Hibernate'
stage 'Artifact Generator'
stage 'Pre Prod Deployer'
stage 'Prod Deployer'
