stage 'Code Stability'
build 'CodeStability'
stage 'Code Quality'
build 'TestExecutorSpring3Hibernate'
build 'CodeQualitySpring3Hibernate'
build 'CodeCoverageSpring3Hibernate'
stage 'Artifact Generator'
stage 'Pre Prod Deployer'
stage 'Prod Deployer'
